import { useRouter } from 'next/router'
import type { NextPage } from 'next'
import Head from 'next/head'
import MultiActionAreaCard from '../../components/blogCard'
import BlogCardList from '../../components/blogCardList'
import Header from '../../components/header'
import styles from '../../styles/Home.module.css'
import { BlogPage } from '../../components/blogPage'

export const Blog = ()=> {
    const router = useRouter();
    const { id } = router.query;
    console.log(id)
    console.log("idddddd");
    const stringifiedId = (id?.length == 0 || id == undefined)? (<div>a</div>) : (<BlogPage id={id.toString()}></BlogPage>)
    console.log(stringifiedId);
    return (
    <div className={styles.container}>
      <Head>
        <title>Takk blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header></Header>
      </div>
      
      <main className={styles.main}>
        <div>{stringifiedId}</div>
      </main>
      
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Blog;