import { useRouter } from 'next/router'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import MultiActionAreaCard from '../../components/blogCard'
import BlogCardList from '../../components/blogCardList'
import Header from '../../components/header'
import styles from '../../styles/Home.module.css'

export const Blog = ()=> {
    const router = useRouter()
    const { id } = router.query
    // fecth blog data from id;
    // fetch comment from id;
    return (
    <div className={styles.container}>
      <Head>
        <title>Takk blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header></Header>
      </div>
      
      <main className={styles.main}>
        {id}
      </main>
      
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Blog;